import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TrpcProvider } from "@/app/TrpcProvider";
import { AuthProvider } from "@/app/SessionProvider";
import { Header } from "@/widgets/Header/ui/Header";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50`}
      >
        <div className="min-h-screen flex flex-col">
          <AuthProvider>
            <TrpcProvider>
              <Header />
              <main className="container mx-auto px-4 pb-8 max-w-7xl">
                {children}
              </main>
              <Toaster position="top-right" />
            </TrpcProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
